schema_version = "1.0.0"

id = "ranato"
version = "0.0.1"
name = "Ranato"
tagline = "Blender implementation of Algebraic Smooth Occluding Contours paper"
maintainer = "Kevin Ha"
type = "add-on"

blender_version_min = "4.5.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

platforms = ["windows-x64"]
wheels = [
  "./wheels/cholespy-2.1.0-cp311-cp311-win_amd64.whl"
]