"""
twelve_split_spline.py
Methods to generate a quadratic surface with twelve split Powell-Sabin basis
coefficients
"""

import src.quadratic_spline_surface.PS12_patch_coeffs
import src.quadratic_spline_surface.PS12tri_bounds_coeffs
import src.core.common

import src.core.line_segment
import src.core.polynomial_function
import src.core.rational_function

from src.quadratic_spline_surface.quadratic_spline_surface import *
from src.quadratic_spline_surface.position_data import *

from igl import per_vertex_normals


class TwelveSplitSplineSurface(QuadraticSplineSurface):
    """
    A piecewise quadratic surface generated by twelve-split Powell-Sabin.

    Supports:
    - quadratic spline surface operations
    - vertex position updates
    """
    def __init__():
        """

        """
        V: np.ndarray
        # contains logic that constructs VF representation from UV coordinates
        # versus directly from position data
